name: Trigger Local Script on Push

on:
  push:
    branches:
      - main  # Trigger only on pushes to the 'main' branch

jobs:
  trigger-script:
    runs-on: ubuntu-latest  # or windows-latest if needed

    steps:
      - name: Send GET request to local server
        run: |
          curl -X GET https://15c4-41-64-173-138.ngrok-free.app/run-script
